name: PHP MySQL containers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-8_1-fpm-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.1-fpm, 8.1-fpm-alpine, 8.1-fpm-alpine3.20
          registry: docker.io
          dockerfile: 8.1/alpine/fpm/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_1-fpm-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.1-fpm-bullseye
          registry: docker.io
          dockerfile: 8.1/bullseye/fpm/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_1-cli-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.1-cli, 8.1-cli-alpine, 8.1-cli-alpine3.20
          registry: docker.io
          dockerfile: 8.1/alpine/cli/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_1-cli-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.1-cli-bullseye
          registry: docker.io
          dockerfile: 8.1/bullseye/cli/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_1-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.1, 8.1-alpine, 8.1-alpine3.20
          registry: docker.io
          dockerfile: 8.1/alpine/plain/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_1-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.1-bullseye
          registry: docker.io
          dockerfile: 8.1/bullseye/plain/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_2-fpm-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.2-fpm, 8.2-fpm-alpine, 8.2-fpm-alpine3.20
          registry: docker.io
          dockerfile: 8.2/alpine/fpm/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_2-fpm-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.2-fpm-bullseye
          registry: docker.io
          dockerfile: 8.2/bullseye/fpm/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_2-cli-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.2-cli, 8.2-cli-alpine, 8.2-cli-alpine3.20
          registry: docker.io
          dockerfile: 8.2/alpine/cli/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_2-cli-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.2-cli-bullseye
          registry: docker.io
          dockerfile: 8.2/bullseye/cli/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_2-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.2, 8.2-alpine, 8.2-alpine3.20
          registry: docker.io
          dockerfile: 8.2/alpine/plain/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_2-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.2-bullseye
          registry: docker.io
          dockerfile: 8.2/bullseye/plain/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_3-fpm-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.3-fpm, 8.3-fpm-alpine, 8.3-fpm-alpine3.20
          registry: docker.io
          dockerfile: 8.3/alpine/fpm/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_3-fpm-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.3-fpm-bullseye
          registry: docker.io
          dockerfile: 8.3/bullseye/fpm/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_3-cli-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.3-cli, 8.3-cli-alpine, 8.3-cli-alpine3.16
          registry: docker.io
          dockerfile: 8.3/alpine/cli/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_3-cli-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.3-cli-bullseye
          registry: docker.io
          dockerfile: 8.3/bullseye/cli/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_3-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.3, 8.3-alpine, 8.3-alpine3.20
          registry: docker.io
          dockerfile: 8.3/alpine/plain/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-8_3-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/php-mysql
          tags: 8.3-bullseye
          registry: docker.io
          dockerfile: 8.3/bullseye/plain/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}